default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: BigYin_development
  pool: 5

test:
  <<: *default
  database: BigYin_test

production:
  <<: *default
  database: BigYin_production
  username: BigYin
  password: <%= ENV['BIGYIN_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>