development:
  # the jquery_sdk version you want to use, read up on it here:
  # https://transloadit.com/blog/2013/02/transloadit-javascript-plugin-and-jquery-1-9
  # defaults to latest
  # use "v1.0.0" if you need IE6 support (using jQuery < 1.9)
  jquery_sdk_version: 'v2-latest'
  auth:
    key     : <%= ENV['TRANSLOADIT_KEY'] %>
    secret  : <%= ENV['TRANSLOADIT_SECRET'] %> # this is optional, but highly recommended, https://transloadit.com/docs/authentication
    duration: 1800 # 30 minute validity period for signed upload forms

  templates:
    # template identified by template_id
    s3_store: <%= ENV['TRANSLOADIT_TEMPLATE'] %>

    # template defined inline
    vm_encoding_video_template:
      steps:
        video:
          use: ":original"
          robot: "/video/encode"
          result: true
          ffmpeg_stack: v2.2.3
          preset: iphone
          ffmpeg:
            t: 5
        screenshot:
          use: ":original"
          robot: "/video/thumbs"
          result: true
          count: 1
        export:
          use: video
          robot: "/s3/store"
          key: <%= ENV['S3_ACCESS_KEY_ID'] %>
          secret: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
          bucket: 'vmdev'

production:
  # the jquery_sdk version you want to use, read up on it here:
  # https://transloadit.com/blog/2013/02/transloadit-javascript-plugin-and-jquery-1-9
  # defaults to latest
  # use "v1.0.0" if you need IE6 support (using jQuery < 1.9)
  jquery_sdk_version: 'v2-latest'
  auth:
    key     : <%= ENV['TRANSLOADIT_KEY'] %>
    secret  : <%= ENV['TRANSLOADIT_SECRET'] %> # this is optional, but highly recommended, https://transloadit.com/docs/authentication
    duration: 1800 # 30 minute validity period for signed upload forms

  templates:
    # template identified by template_id
    s3_store: <%= ENV['TRANSLOADIT_TEMPLATE'] %>

    # template defined inline
    vm_encoding_video_template:
      steps:
        video:
          use: ":original"
          robot: "/video/encode"
          result: true
          ffmpeg_stack: v2.2.3
          preset: iphone
          ffmpeg:
            t: 5
        screenshot:
          use: ":original"
          robot: "/video/thumbs"
          result: true
          count: 1
        export:
          use: video
          robot: "/s3/store"
          key: <%= ENV['S3_ACCESS_KEY_ID'] %>
          secret: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
          bucket: 'vmprod'